### ISSUE TITLE
add menu

### ISSUE THREAD

**Issue by ehf5307** [ehf5307/ISTE-438-NEO4j#3]
menu should have  home, people list, and movie list

**Comment by ehf5307** [comment]
menu created - needs to be styled

**Comment by m4ttr33d** [comment]
This is the top menu correct?

**Comment by ehf5307** [comment]
As in is it the right links? Yes.

**Comment by m4ttr33d** [comment]
Got it, I added it to all pages except the movies.ejs and person.ejs.

**Comment by ehf5307** [comment]
Good shit. I'll check it out when I get home
